# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: fem fluids
author: Martien Hulsen, Nick Jaensson, Patrick Anderson
email: 'n.o.jaensson@tue.nl'
logo: FEMfluids_logo.svg
copyright: "Eindhoven University of Technology, CC BY 4.0"

# Only build files in the ToC to avoid building README, etc.
only_build_toc_files: true

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
    - references.bib

# Sphinx settings for HTML formatting
sphinx:
  config:
    language: en
    myst_all_links_external: true
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js
      - _static/custom.js  # Add custom JavaScript for centering equations
    mathjax3_config:
      loader: {load: ['[tex]/autoload', '[tex]/ams', '[tex]/boldsymbol']}      
      tex:
        packages: {'[+]': ['autoload', 'ams', 'physics', 'boldsymbol']}
        tags: 'ams'
        macros:
          "kB": "k_\\mathrm{B}"
          "Rn": "\\mathrm{Re}"
          "bm": "\\mathbf"
          "inprod": "\\innerproduct"
          "diff": "\\pdv"
          "vek": ["\\boldsymbol{#1}", 1]
          "sumNm": "\\sum\\limits_{i=1}^{N-1}"
          "sumN": "\\sum\\limits_{i=1}^N"
          "IO": "\\int\\limits_{\\Omega}"
          "IG": "\\int\\limits_{\\Gamma}"
          "IOt": "\\int\\limits_{\\Omega(t)}"
          "IGt": "\\int\\limits_{\\Gamma(t)}"
          "pdifff": ["\\frac{\\partial^3 #1}{\\partial {#2}^3}", 2]
          "pdiff": ["\\frac{\\partial^2 #1}{\\partial {#2}^2}", 2]
          "pdif": ["\\frac{\\partial #1}{\\partial #2}", 2]
          "half": "\\mbox{\\(\\frac{1}{2}\\)}"
          "ten": "\\pmb"
          "derivmat": ["\\frac{D#1}{D#2}", 2]
          "lderivmat": ["D#1/D#2", 2]
          "nao": "\\vek\\nabla"
          "divg": "\\mathop {\\rm div}\\nolimits"
          "grad": "\\mathop {\\rm grad}\\nolimits"
          "rot": "\\mathop {\\rm rot}\\nolimits"
          "curl": "\\mathop {\\rm curl}\\nolimits"
          "tr": "\\mathop {\\rm tr}\\nolimits"
          "plderiv": ["\\partial #1 / \\partial #2", 2]
          "pderiv": ["\\frac{\\partial #1}{\\partial #2}", 2]
          "dpderiv": ["\\dfrac{\\partial #1}{\\partial #2}", 2]
          "lderiv": ["d #1 / d #2", 2]
          "deriv": ["\\frac{d #1}{d #2}", 2]
          "mat":  ["\\mathsf{#1}", 1]
          "matt": ["\\mathsf{#1}", 1]
          "mats": ["{\\enclose{bottom}[padding=0,thickness=0.06em]{#1}}\\!_{\\hspace{2pt}#2}", 2]
          "col": ["\\mathsf{#1}", 1]
          "coll": ["\\mathsf{#1}", 1]
          "cols": ["\\mathsf{#1}", 1]
          "tsum": "{\\textstyle\\sum}"
          "DR": ["\\textrm{DR}"]
          "inv": "{}^{-1}"
          "invT": "{}^{-T}"
          "colnabla": "\\mathsf{\\nabla}"

    html_theme_options:
      logo:
        image_light: FEMfluids_logo.svg
        image_dark: FEMfluids_logo_dark.svg

  extra_extensions:
    - sphinx_proof
    - sphinx_exercise
    - sphinx_togglebutton

# Parse for processing LaTeX-style math
parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - strikethrough
    - attrs_inline
    - attrs_block
    - html_image
    - linkify

# Information about where the book exists on the web
repository:
  url:   # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

